eni_qcm_stagiaire:
    resource: "@EniQcmStagiaireBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@EniQcmStagiaireBundle/Controller/"
    type:     annotation

user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"