eni_qcm_formateur_homepage:
    path:     /helloo/{name}
    defaults: { _controller: EniQcmFormateurBundle:Default:index }
    
eni_qcm_formateur:
    resource: "@EniQcmFormateurBundle/Controller/"
    type:     annotation


eni_qcm_formateur_after_login:
    resource: "@EniQcmFormateurBundle/Redirection/"
    defaults: { _controller: EniQcmFormateurBundle:AfterLoginRedirection:onAuthenticationSuccess }
